### PR TITLE
Fix syntax error

### PR DESCRIPTION
**Pull request by yuki24**
This makes me wonder whether you have ever run any of the code in the README..

### CODE REVIEW

**Comment by vasilakisfil** [comment]
I have been copying pasting the code, not sure how I missed that. The code however can always be found in the repo.

**Comment by yuki24** [comment]
So maybe it's possible that even the original book has the syntax error?

**Comment by vasilakisfil** [comment]
hmm which book? I have been copying pasting the code from the actual code found inside the Rails app in this repo to the Readme so maybe I missed that somehow.

The original code should be ok because otherwise tests wouldn't run.

**Comment by yuki24** [comment]
I haven't read the book or seen the repo at all. I just assumed the original code had a syntax error, but I guess I just don't have enough context to see the whole picture. If the original repo is tested then ignore my comment above.

**Pull request merged**
